services:
  mediaflow-proxy:
    image: mhdzumair/mediaflow-proxy
    container_name: mediaflow-proxy
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - API_PASSWORD=${MEDIAFLOW_PASSWORD}
      - MPD_LIVE_STREAM_DELAY=30
      - DASH_SEGMENT_CACHE_TTL=${MEDIAFLOW_MPD_LIVE_INIT_CACHE_TTL}
  m3u-proxy:
    build: .
    container_name: m3u-proxy
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - SOURCE_PLAYLIST_URL=${SOURCE_PLAYLIST_URL}
      - MEDIAFLOW_URL=${MEDIAFLOW_URL}
      - MEDIAFLOW_PASSWORD=${MEDIAFLOW_PASSWORD}
      - CACHE_TTL_SECONDS=3600
      - WATCH_CACHE_TTL_SECONDS=300
      - PLAYLIST_PASSWORD=${PLAYLIST_PASSWORD}
      - PUBLIC_URL=${PUBLIC_URL}
    depends_on:
      - mediaflow-proxy
